# Generated by Django 6.0.3 on 2026-05-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitSpanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span', models.PositiveIntegerField(verbose_name='Długość sekwencji')),
                ('sequence', models.CharField(max_length=255, verbose_name='Sekwencja cyfr')),
                ('user_answer', models.CharField(max_length=255, verbose_name='Odpowiedź uczestnika')),
                ('correct', models.BooleanField(verbose_name='Poprawna odpowiedź')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digit_span_results', to='survey.user', verbose_name='Uczestnik')),
            ],
            options={
                'verbose_name': 'Wynik Digit Span',
                'verbose_name_plural': 'Wyniki Digit Span',
            },
        ),
    ]
