# Generated by Django 6.0.3 on 2026-05-12 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SARTResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_errors', models.PositiveIntegerField(verbose_name='Błędy komisji')),
                ('omission_errors', models.PositiveIntegerField(verbose_name='Błędy pominięcia')),
                ('mean_reaction_time', models.FloatField(blank=True, null=True, verbose_name='Średni czas reakcji (ms)')),
                ('trials_data', models.JSONField(verbose_name='Dane prób')),
                ('sequence', models.CharField(max_length=255, verbose_name='Sekwencja cyfr')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sart_results', to='survey.user', verbose_name='Uczestnik')),
            ],
            options={
                'verbose_name': 'Wynik SART',
                'verbose_name_plural': 'Wyniki SART',
            },
        ),
    ]
