# Generated by Django 6.0.3 on 2026-05-12 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        ('tasks', '0002_sartresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbalFluencyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Kategoria fluencji werbalnej',
                'verbose_name_plural': 'Kategorie fluencji werbalnej',
            },
        ),
        migrations.CreateModel(
            name='VerbalFluencyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trials_data', models.JSONField(verbose_name='Dane prób')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbal_fluency_results', to='survey.user', verbose_name='Uczestnik')),
            ],
            options={
                'verbose_name': 'Wynik fluencji werbalnej',
                'verbose_name_plural': 'Wyniki fluencji werbalnej',
            },
        ),
        migrations.CreateModel(
            name='VerbalFluencyTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, verbose_name='Litera')),
                ('time_limit', models.PositiveIntegerField(default=60, verbose_name='Limit czasu (s)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='tasks.verbalfluencycategory', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Próba fluencji werbalnej',
                'verbose_name_plural': 'Próby fluencji werbalnej',
                'unique_together': {('letter', 'category')},
            },
        ),
    ]
