# Generated by Django 6.0.3 on 2026-05-12 02:21

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(verbose_name='Kolejność opcji')),
                ('label', models.CharField(max_length=255, verbose_name='Tekst opcji')),
            ],
            options={
                'verbose_name': 'Opcja odpowiedzi',
                'verbose_name_plural': 'Opcje odpowiedzi',
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nazwa typu treści')),
            ],
            options={
                'verbose_name': 'Typ treści KFW',
                'verbose_name_plural': 'Typy treści KFW',
            },
        ),
        migrations.CreateModel(
            name='SFVPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nazwa platformy')),
            ],
            options={
                'verbose_name': 'Platforma KFW',
                'verbose_name_plural': 'Platformy KFW',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.PositiveIntegerField(verbose_name='Wiek')),
                ('gender', models.CharField(choices=[('male', 'Mężczyzna'), ('female', 'Kobieta'), ('other', 'Inna')], max_length=16, verbose_name='Płeć')),
                ('education', models.CharField(choices=[('primary', 'Podstawowe'), ('secondary', 'Średnie'), ('higher', 'Wyższe')], max_length=16, verbose_name='Wykształcenie')),
                ('is_watching_SFV', models.BooleanField(verbose_name='Czy ogląda KFW')),
                ('is_on_mobile', models.BooleanField(default=False, verbose_name='Czy korzysta z urządzenia mobilnego')),
                ('added_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Uczestnik',
                'verbose_name_plural': 'Uczestnicy',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255, verbose_name='Kategoria')),
                ('question_text', models.CharField(max_length=255, verbose_name='Treść pytania')),
                ('answer_options', models.ManyToManyField(to='survey.answeroption', verbose_name='Opcje odpowiedzi')),
            ],
            options={
                'verbose_name': 'Pytanie',
                'verbose_name_plural': 'Pytania',
            },
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('daily_SFV_time', models.IntegerField(choices=[(15, 'Poniżej 0,5 godziny'), (30, 'Od 0,5 do 1 godziny'), (90, 'Od 1 do 2 godzin'), (150, 'Od 2 do 3 godzin'), (240, 'Od 3 do 5 godzin'), (360, 'Powyżej 5 godzin')], verbose_name='Średni łączny czas spędzany na KFW dziennie')),
                ('daily_SFV_sessions', models.IntegerField(choices=[(2, 'Od 1 do 2 sesji'), (4, 'Od 3 do 5 sesji'), (8, 'Od 6 do 10 sesji'), (12, 'Powyżej 10 sesji')], verbose_name='Średnia liczba sesji KFW dziennie')),
                ('preferred_content_types', models.ManyToManyField(to='survey.contenttype', verbose_name='Preferowane treści')),
                ('preferred_platforms', models.ManyToManyField(to='survey.sfvplatform', verbose_name='Preferowane platformy KFW')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='survey.user', verbose_name='Uczestnik')),
            ],
            options={
                'verbose_name': 'Nawyki',
                'verbose_name_plural': 'Nawyki',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255, verbose_name='Odpowiedź')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question', verbose_name='Pytanie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_answers', to='survey.user', verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Odpowiedź',
                'verbose_name_plural': 'Odpowiedzi',
                'unique_together': {('question', 'user')},
            },
        ),
    ]
